### ISSUE TITLE
I'm confused now, is it Haskel?

### ISSUE THREAD

**Issue by erlang-developer** [well-ironed/fe#8]
I think not, Im new in programming in Elixir, can we rename `"FE.Review"` to `"FE.These"` ?

**Comment by studzien** [comment]
Hi!
Thanks for the interest in the project!
The idea behind the name of the `Review` type is to make it more specific and limit its purpose to assess the output of computation.
But not just limited to successful or erroneous output, like in case of `FE.Result`, but also to indicate that the computation returned something meaningful, but that there were some issues with that computation.
We could say that `Result` is a specific implementation of `Either` type. In the same vein, `Review` is a specific implementation of `These`.
